# Generated by Django 3.2.15 on 2022-12-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_sana', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='PlantaEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agronomia.enfermedad', verbose_name='Enfermedad')),
                ('id_planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agronomia.planta', verbose_name='Planta')),
            ],
            options={
                'verbose_name': 'Plan Enfermedad',
                'verbose_name_plural': 'Plantas Efermedades',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('id_carga_entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agronomia.cargaentrenamiento', verbose_name='Carga Entrenamiento')),
            ],
        ),
        migrations.AddField(
            model_name='cargaentrenamiento',
            name='id_enfermedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_agronomia.enfermedad', verbose_name='Enfermedad'),
        ),
        migrations.AddField(
            model_name='cargaentrenamiento',
            name='id_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_agronomia.planta', verbose_name='Planta'),
        ),
    ]
